language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"

services:
  - mongodb
  
addons:
  apt:
    sources:
    - mongodb-3.0-precise

before_script:
  - npm start
  - sleep 5

script: npm test
