language: node_js
node_js:
  - "stable"
  - "8"
  - "6"
  - "4"

install:
- npm install chai
- npm install chai-http
- npm install -g mocha

services:
- mongodb

script:
  - node app.js &
  - sleep 5
  - mocha tests/basic.js
